default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  pool: 5
  username: postgres
  role: adam
  
# this is for humans
development:
  <<: *default
  database: blog_project_dev


# this is for robots - do not touch
# tell the robot to use it with  'rake test'
test:
  <<: *default
  database: blog_project_test
